# Generated by Django 5.1.7 on 2025-03-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_locale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocalemodel',
            old_name='CEP',
            new_name='postal_code',
        ),
    ]
