# Generated by Django 5.1.7 on 2025-03-22 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_locale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('full_name', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='avatars/images')),
                ('identify', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(max_length=18)),
                ('status', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_locale.userlocalemodel')),
            ],
        ),
    ]
