# Generated by Django 5.1.7 on 2025-03-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
        ('user_locale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatarmodel',
            name='user_locale',
        ),
        migrations.AddField(
            model_name='avatarmodel',
            name='user_locale',
            field=models.ManyToManyField(to='user_locale.userlocalemodel'),
        ),
    ]
