# Generated by Django 5.1.7 on 2025-03-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0003_rename_user_avatarmodel_fk_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarmodel',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
