# Generated by Django 5.1.7 on 2025-03-29 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatar', '0004_alter_avatarmodel_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('07b57947-7279-4aa6-aeab-6f2f971d8843'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('fk_avatar', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.avatarmodel')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
