# Generated by Django 5.1.7 on 2025-04-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNonConfirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='codemodel',
            old_name='userd',
            new_name='used',
        ),
        migrations.AddField(
            model_name='codemodel',
            name='fk_user_non_confirmed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usernonconfirmed'),
            preserve_default=False,
        ),
    ]
